apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunkerweb-ui
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bunkerweb-ui
  template:
    metadata:
      labels:
        app: bunkerweb-ui
    spec:
      serviceAccountName: sa-bunkerweb
      containers:
        - name: bunkerweb-ui
          image: bunkerity/bunkerweb-ui:1.6.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7000
              protocol: TCP
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ADMIN_USERNAME
              value: "yacine"
            - name: "ADMIN_PASSWORD"
              value: "th2Sup2r4dm1N!"
            - name: KUBERNETES_MODE
              value: "YES"
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: bunkerweb-app
                  key: host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: bunkerweb-app
                  key: port
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: bunkerweb-app
                  key: dbname
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bunkerweb-app
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bunkerweb-app
                  key: password
            - name: BUNKERWEB_INSTANCES # next to the major 1.6, its mandatory to add this env var to successfully connect to the bunkerweb pods.
              value: "" # We don't need to specify the BunkerWeb instance here as they are automatically detected by the ingress controller

            - name: "DATABASE_URI"
              value: "postgresql://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
            # - name: "DATABASE_URI"
            #   value: "postgresql://bunkerweb:LkgSGKNn80ffJ99K3SbnHlSWKYvd4WpEpMZUCN67VhtZyHDxlFt1bC2fFcoADftc@bunkerweb-rw:5432/bunkerweb"
      #     volumeMounts:
      #       - name: instances-conf
      #         mountPath: "/usr/share/bunkerweb/ui/src/Instances.py"
      #         subPath: Instances.py
      # volumes:
      #   - name: instances-conf
      #     configMap:
      #       name: instances-conf