apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
            
configMapGenerator:
  - name: instances-conf
    files:
      - conf/Instances.py
